apiVersion: v1
kind: Service
metadata:
  name: export-app-service
  labels:
    app: export-app-service  
spec:
  selector:
    app: export-app
  ports:
  - port: 8080
    targetPort: 8080 
  type: LoadBalancer
