apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: export-app-sa
subjects:
- kind: ServiceAccount
  name: export-app-sa
  namespace: n1
roleRef:
  kind: ClusterRole
  name: export-app-sa
  apiGroup: rbac.authorization.k8s.io
 