apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: export-app-sa  
  annotations:
    export.app.control/prune: "true"   
subjects:
- kind: ServiceAccount
  name: export-app-sa
  namespace: n1
roleRef:
  kind: Role
  name: export-app-sa
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: export-app-sa 
  namespace: n1
  labels:
    export-app-sa: export-app
rules: 
- apiGroups:
  - '*'
  resources:
  - '*'
  verbs:
  - get
  - list
- apiGroups:
  - batch
  resources:
  - jobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups: 
  - ""
  resources:
  - extracts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ""
  resources:
  - extracts/finalizers
  verbs:
  - update
- apiGroups:
  - ""
  resources:
  - extracts/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - rolebindings
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - roles
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: export-app-sa
  namespace: n1
  labels:
    export-app-sa: export-app
---